### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by wreis**

### CODE REVIEW

**Comment by abraxxa** [comment]
Why dis you move JSON from an author to an install dependency in addition to JSON::MaybeXS?

**Comment by wreis** [comment]
Because it is not just an author dep:

https://www.cpantesters.org/cpan/report/ad067954-1191-11e9-a2f3-be2a49ab7630 # reproduced it too in a project

however, I agree there might be a better fix. Will push in a bit.

**Comment by abraxxa** [comment]
I'd say Message::Passing::Role::CLIComponent should use JSON::MaybeXS instead.
Ah, you came to the same conclusion, thanks!

**Comment by abraxxa** [comment]
Can you please squash the two commits, will rebase it then.

**Comment by wreis** [comment]
Done.

**Comment by abraxxa** [comment]
Thanks!

**Pull request merged**
